version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  gateway:
    build: .
    ports: ["3000:3000"]
    environment:
      - AUTH_HOST=auth-service
      - USERS_HOST=users-service
      - ROOMS_HOST=rooms-service
      - RESOURCES_HOST=resources-service
      - BOOKINGS_HOST=bookings-service
      - JWT_SECRET=sua_chave_super_secreta_aqui
    depends_on:
      - auth-service
      - users-service
      - rooms-service
      - resources-service
      - bookings-service
    networks:
      - app-network

  auth-service:
    build: ./packages/auth-service
    environment:
      - DB_HOST=postgres
      - DB_NAME=auth_db
      - USERS_HOST=users-service
      - JWT_SECRET=sua_chave_super_secreta_aqui
    depends_on:
      - postgres
    networks:
      - app-network

  users-service:
    build: ./packages/users-service
    environment:
      - DB_HOST=postgres
      - DB_NAME=users_db
    depends_on:
      - postgres
    networks:
      - app-network

  rooms-service:
    build: ./packages/rooms-service
    environment:
      - DB_HOST=postgres
      - DB_NAME=rooms_db
    depends_on:
      - postgres
    networks:
      - app-network

  resources-service:
    build: ./packages/resources-service
    environment:
      - DB_HOST=postgres
      - DB_NAME=resources_db
    depends_on:
      - postgres
    networks:
      - app-network

  bookings-service:
    build: ./packages/bookings-service
    environment:
      - DB_HOST=postgres
      - DB_NAME=bookings_db
      - ROOMS_HOST=rooms-service
    depends_on:
      - postgres
    networks:
      - app-network

  notification-service:
    build: ./packages/notification-service
    environment:
      - MAIL_HOST=smtp.exemplo.com
      # ... configurações de email
    networks:
      - app-network

networks:
  app-network:
    driver: bridge